/** Mashina o'qiydigan xato kodlari. Mobil shu kod bo'yicha tarjima qiladi. */
export const ErrorCode = {
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMIT: 'AUTH_OTP_RATE_LIMIT',
  /** SMS shlyuzi kodni yubora olmadi — foydalanuvchi bekorga kutmasin. */
  AUTH_OTP_SEND_FAILED: 'AUTH_OTP_SEND_FAILED',
  RATE_LIMIT: 'RATE_LIMIT',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_BAD_CREDENTIALS: 'AUTH_BAD_CREDENTIALS',
  AUTH_PHONE_TAKEN: 'AUTH_PHONE_TAKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_SAME_PASSWORD: 'AUTH_SAME_PASSWORD',
  FORBIDDEN: 'FORBIDDEN',
  NOT_MEMBER: 'NOT_MEMBER',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_CREDIT_LIMIT: 'ORDER_CREDIT_LIMIT',
  ORDER_CANCEL_PENALTY: 'ORDER_CANCEL_PENALTY',
  DELIVERY_INVALID_TRANSITION: 'DELIVERY_INVALID_TRANSITION',
  DELIVERY_DRIVER_BUSY: 'DELIVERY_DRIVER_BUSY',
  DELIVERY_SIGNATURE_REQUIRED: 'DELIVERY_SIGNATURE_REQUIRED',
  DELIVERY_STALE: 'DELIVERY_STALE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INTERNAL: 'INTERNAL',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
